### ISSUE TITLE
CO2 and stuff notes

### ISSUE THREAD

**Issue by bpbond** [stephpenn1/STEEP-CF#12]
I am re-reading the Abramoff 2018 and 2022 papers...

- [ ] In the 2022 paper, they did a type of parameter sensitivity exercise! Huh. See Figure S2. But your analysis goes much further.
- [ ] CO2: when I run the Millenial example RMarkdown (so not Leeya's work) the CO2 outputs looks like what we'd expect:
<img width="700" alt="Screenshot 2023-11-16 at 7 24 48 AM" src="https://github.com/stephpenn1/STEEP-CF/assets/1956468/39e8b1a5-94ec-44d6-a43b-0704eedc9243">
So why is it producing the funky behavior we're seeing?!? Hmm.

**Comment by bpbond** [comment]
AH HA! @stephpenn1 

From the `model_tutorial.Rmd` file:

```r
#Define function which plots the modeled CO2 emissions over time
##CO2 emissions are cumulative, so we have to take the difference between timesteps to plot the CO2 emission rate
plot.co2 <- function(output){
  plot(output[1:(dim(output)[1]-1),"time"], 
       diff(output[,"CO2"]), 
       xlab="time (days)", 
       ylab="co2 (gC m-2 d-1)", 
       col=1, 
       type="l")
}
```

Who the heck decided that CO2 emissions should be _cumulative_, and why is this not documented in the papers?!? 😐 

Anyway, now we know. You can use the `diff` function (see above) to calculate the differences between timesteps, and that will be the output we care about.

**Comment by stephpenn1** [comment]
Nice investigative work! I will use that diff function for our output!
