### ISSUE TITLE
What on earth

### ISSUE THREAD

**Issue by bpbond** [stephpenn1/STEEP-CF#4]
What dark magic is this
```r
params <- lapply(runlist_final[-1], `[`, r)
```
...oh OK, I get it. Wow! 👏

**Comment by bpbond** [comment]
...just FYI more common would be to use `mapply` for this. But your way totally works.

**Comment by leeyap** [comment]
Ha! Always good to see a "what on earth" issue. I'll add some comments to clarify what's happening.

**Comment by bpbond** [comment]
🙏
